services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\InvoiceFormatFixationBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'
